### ISSUE TITLE
Error in descr. of subprojects

### ISSUE THREAD

**Issue by klartext** [mmottl/ocaml-makefile#2]
Handling subprojects:

define PROJ_p1
  SOURCES="foo.ml main.ml"
  RESULT="p1"
  OCAMLFLAGS="-unsafe"
endef
export PROJ_p1

Does NOT work.
Problematic line:
  SOURCES="foo.ml main.ml"

should be:
  SOURCES=foo.ml main.ml
Without '"' it does work.

**Comment by mmottl** [comment]
Thanks, done.
