### ISSUE TITLE
Failure to build OPAM on OSX with GNU Make 3.81

### ISSUE THREAD

**Issue by AltGr** [mmottl/ocaml-makefile#3]
See https://github.com/ocaml/opam/issues/2103
I don't have a clear idea what's going wrong, not sure OCamlMakefile is in cause, but any help would be appreciated!

**Comment by mmottl** [comment]
I'm afraid, but I wasn't able to replicate the problem.  My build of OPAM 1.2.1 on Mac OS X with GNU Make 3.81 finishes successfully.

**Comment by AltGr** [comment]
Ok, thanks for testing!
