### ISSUE TITLE
How to build and run a testsuite

### ISSUE THREAD

**Issue by adamjstewart** [mmottl/ocaml-makefile#5]
I'm interested in using `OCamlMakefile` for a small project, but I'm wondering how to integrate my testsuite with it. I'm envisioning the following directory structure:
```
src/*.ml[ly]
test/*.ml
```
I would like to be able to write a Makefile like the following:
```make
SOURCES = <everything in src>
TESTS = <everything in test>

include OCamlMakefile
```
I would then like to be able to run the following commands:
```
$ make      # only build binaries
$ make test # build and run test files
```
Any suggestions for how to write a `test` target? Or any interest in supporting these features in `OCamlMakefile` itself?

**Comment by mmottl** [comment]
I'd strongly suggest switching to a different build tool.  `OCamlMakefile`, though likely working fine, is ancient.  The easiest way to start is probably [jbuilder](https://jbuilder.readthedocs.io/en/latest).  It makes building applications and libraries efficiently and correctly almost trivial.

**Comment by adamjstewart** [comment]
I appreciate the honesty! The project I'm building is for a class, not something I plan on distributing, so I think I'm actually going to handwrite the Makefile myself. It'll be a good exercise in understanding how to compile OCaml modules.

**Comment by mmottl** [comment]
I see.  `make` is notoriously bad when it comes to projects spanning multiple directories.  You may have to use recursive calls to `make`, i.e. have separate `Makefile`s in each directory and call them from a `Makefile` in a parent directory.

**Comment by adamjstewart** [comment]
That's exactly what I did. See https://github.com/adamjstewart/prolog if you're curious.
