### ISSUE TITLE
Can't libinstall when using subprojects

### ISSUE THREAD

**Issue by ghost** [mmottl/ocaml-makefile#8]
Hello,

At example:  https://github.com/mmottl/ocaml-makefile/tree/master/threads
When changing the default target to be:
```
# Default target to use
all: bcl
```
And invoking: "libinstall",  get the following "No rule to make target 'all', needed by 'libinstall":
```
$ make libinstall
make[1]: Entering directory '/home/threads'
make[2]: Entering directory '/home/threads'
make[2]: *** No rule to make target 'all', needed by 'libinstall'.  Stop.
make[2]: Leaving directory '/home/threads'
make[1]: *** [OCamlMakefile:1227: subproj_ex1] Error 2
make[1]: Leaving directory '/home/threads'
make: *** [Makefile:32: libinstall] Error 2
```

**Comment by mmottl** [comment]
I'm afraid, but I don't really develop OCamlMakefile anymore.  You are much better off switching to [Dune](https://github.com/ocaml/dune).  But feel free to submit any patches you might need.
